Add DeleteForStudentsAndGroupsCommand and relevant test cases
AY2324S1-CS2103T-W15-2/tp pull request #113
Opened 2023-10-14 12:35 UTC by zannloo

Parser is not yet updated for this command.

2023-10-14 18:22 UTC, mingyuanc approved these changes
LGTM

2023-10-15 11:13 UTC, mingyuanc requested changes

2023-10-15 11:13 UTC, mingyuanc commented on src/main/java/seedu/address/logic/newcommands/DeleteForStudentsAndGroupsCommand.java
> +                ChildOperation<Student> target = StateManager.groupChildOperation(root, absolutePath);
Please change to the new methods

2023-10-16 03:56 UTC, mingyuanc submitted a review, later dismissed
LGTM

2023-10-16 10:20 UTC, NereusWB922 requested changes
Need changes for Parser

2023-10-16 10:20 UTC, NereusWB922 commented on src/main/java/seedu/address/logic/parser/newcommandparser/DeleteForStudentsAndGroupsCommandParser.java
> +        }
Should check this in command execute.
Consider the situation: relative path = ../ , u won't know what is this refer to without current path

2023-10-16 12:24 UTC, NgChunMan approved these changes
LGTM.

2023-10-16 12:47 UTC, NereusWB922 approved these changes

2023-10-16 12:49 UTC, merged