Edit UG
AY2324S1-CS2103T-W15-2/tp pull request #262
Opened 2023-11-05 09:23 UTC by zannloo

2023-11-07 10:15 UTC, Nid21cs requested changes

2023-11-07 10:15 UTC, Nid21cs commented on docs/UserGuide.md
> +  - `allStu` which adds **individual** tasks to all students under within the group directory.
Should just be under or within not both?

2023-11-07 12:29 UTC, zannloo commented on docs/UserGuide.md
> +    - - **Note:** StudentId here corresponds to the last 5 place of an NUS student's matriculation number and is not
However, the last 5 is a mix of digits and alphabet. But good suggestion that suggests that readers may have confusion when reading this part. Will think further on better alternatives!

2023-11-07 12:54 UTC, merged

2023-11-08 14:17 UTC, NgChunMan reviewed
LGTM. Just a few minor changes need to be made.

2023-11-08 14:17 UTC, NgChunMan commented on docs/UserGuide.md
> +  - [Invalid destination path.](#mistake-2--invalid-path)
This link is invalid. Nothing happens after clicking on it. Perhaps the link contains a redundant '-', which causes it to be invalid.