Update PPP
AY2324S1-CS2103T-W15-2/tp pull request #270
Opened 2023-11-07 11:17 UTC by Nid21cs

Added in contributions in 
-  Team based work
- Add in work done in DG
- Add in code repo link

2023-11-07 17:08 UTC, mingyuanc requested changes

2023-11-07 17:08 UTC, mingyuanc commented on docs/team/nid21cs.md
> +  - How to use User Guide
Cap bro

2023-11-07 17:08 UTC, mingyuanc commented on docs/team/nid21cs.md
> +-  `todo` command
todo got a space before it

2023-11-07 17:08 UTC, mingyuanc commented on docs/team/nid21cs.md
> +- **[Pull Request #269](https://github.com/AY2324S1-CS2103T-W15-2/tp/pull/269)**
bro this cap, all u did was said my model was misspelt

2023-11-08 02:33 UTC, Nid21cs commented on docs/team/nid21cs.md
> +5. **User stories**:
brother i add long time ago start of proj

2023-11-08 04:33 UTC, mingyuanc approved these changes
Apart from all the cap, LGTM

2023-11-08 05:30 UTC, merged