Update manual testing for DG
AY2324S1-CS2103T-W15-2/tp pull request #286
Opened 2023-11-10 03:43 UTC by NgChunMan

2023-11-10 14:11 UTC, mingyuanc requested changes
Do check that the whole file do not repeat the changes that i requested. Other than that, make the changes and push it again, Dont resolve the changes, I will do so myself

2023-11-10 14:11 UTC, mingyuanc commented on docs/DeveloperGuide.md
> +          Expected: If there is no such a group with GroupId, `grp-001`, then an error message will appear at the output box below the command box. Otherwise, all the students in `grp-001` will be di
Yeap something like this for the above one on CD

2023-11-10 14:11 UTC, mingyuanc commented on docs/DeveloperGuide.md
> +    1. Test case: Navigate to the `/data` folder and delete the `profbook.json` file. Then reopen the application.
I know this is what the other team did but follow the other one, ie the screenshot i send in the telegram group. IE the one where they make some changes using commands and it is reflected in the data file

2023-11-11 11:56 UTC, mingyuanc requested changes
Got some changes not done properly! Do not use numbered bullet points cause it looks super super weird

2023-11-11 11:56 UTC, mingyuanc commented on docs/DeveloperGuide.md
> +   1. Condition 1: When the current directory is group directory,
This should be condition 2 ah

2023-11-11 11:56 UTC, mingyuanc commented on docs/DeveloperGuide.md
> +       - Test case: `rm grp-001`<br>
![image](https://github.com/AY2324S1-CS2103T-W15-2/tp/assets/94535035/126f9394-2855-4811-8f5e-e668659b900c)

Expected outcome wrong

2023-11-11 11:56 UTC, mingyuanc commented on docs/DeveloperGuide.md
> +### Editing a student's details or group's details
You did not resolve this ah

2023-11-11 11:56 UTC, mingyuanc commented on docs/DeveloperGuide.md
> +    1. Prerequisites: The display panel is showing the task list of the specific student or group.
You did it for mark task but you did not do for unmark/delete tast

2023-11-11 11:56 UTC, mingyuanc commented on docs/DeveloperGuide.md
> +          Expected: An error message of `Encountered invalid path element: x will be shown.
your missing a back tick

2023-11-11 12:59 UTC, NgChunMan commented on docs/DeveloperGuide.md
> +### Editing a student's details or group's details
Are these two lines (line 1257 and line 1277) not what you referring to?

2023-11-12 11:48 UTC, mingyuanc approved these changes
LGTM!!!!!!

2023-11-12 11:48 UTC, merged